language: python
dist: xenial
matrix:
  allow_failures:
    - os: windows
    - os: osx
    - python: 3.9-dev
  include:
    - python: 3.8
      env:
        - TOX_ENV=py38
    - python: 3.7
      env:
        - TOX_ENV=py37
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.9-dev
      env:
        - TOX_ENV=py39
    - os: osx
      language: generic
      python: 3.7
      env:
        - TOX_ENV=py37
    - os: windows
      language: sh
      python: 3.7
      before_install:
        - choco install python --version=3.7.5
        - choco install nodejs
        - export PATH="/c/Python37:/c/Python37/Scripts:/c/Program Files/nodejs:$PATH"
        - python -m pip install --upgrade pip wheel tox
      env:
        - TOX_ENV=py37
    - python: 3.8
      env:
        - TOX_ENV=py38
        - DOCKER_MB_HOST=2525
      services:
        - docker
      before_install:
        - docker run -p 2525:2525 -p 2526:2526 -p 4525:4525 -p 4545:4545 -p 4546:4546 -d bbyars/mountebank "mb" "--allowInjection"
        - pip install --upgrade tox
    - python: 3.6
      env:
        - TOX_ENV=pypy3.6
    - python: 3.8
      env:
        - TOX_ENV=check-format
    - python: 3.8
      env:
        - TOX_ENV=flake8
    - python: 3.8
      env:
        - TOX_ENV=bandit
    - python: 3.8
      env:
        - TOX_ENV=mypy
    - python: 3.8
      env:
        - TOX_ENV=docs
    - python: 3.6
      env:
        - TOX_ENV=publish-coverage
        - secure: "iBpfQQnq7LqJC9Tc4M7EuRiK5RSZLjsmacp6Ns9obpkkHQyJFWS80760BOD8iBsi9cor5w6z0JzLBIJYLGRZAmUNW7y76K+NKXs9pEn/i6mF7V8rXCzU6tyJ28xH6csNt9KAkoHIbXmt+0TAa4tN+uCRq2c7rHVbuarCfQBVislpJZl9qz61WVvDBfxpefL4VKCkteHxNTGMdZvw0wnc1+RvluNLeuNQ6TpPnJ7iS2FPGXOOMhcj26ZVL5cPMqIwX5IIo2JlWczMqXYWwoN+PC+4YlZclH+c73yl3XcZL9twq4g1cvW39HKAd5QDpQPapLep+3OF39bBiYetlqLUImHgCI/IwufV7RSceW+HUv1rqTVIteglRWhmR1ePZYeuJxLsuGnIbKRJcUnob7spk2Oxwr+ZrvqqC3+ivSpaPQiZjtIp2mdTEvetWm6X7xjMvk8FQKJZedp8CaRO8TEd9U5Cy3XxCA/hXNIThhxWtkpCwqmGs/VGV6Ao6swsuN/z9YxUQ2uIKvml7KwzCj1QYOhpHkdcxRGyTy/xoEUvQ4Vm7XGcrxksUKKBu1K9VCIdANo73w0WwTM6BPSWiMKDMHCUaJFqLiSr3gZwT2oUrPt83f9THdY7hl67NeZB7v0DHm/c4BSXf7nrkWmxREAUd86KRcrdczqe7NIJJGzpkRM="
    - python: 3.8
      sudo: yes
      env:
        - TOX_ENV=py38
        - MBTEST_VERSION=2.1
    - python: 3.8
      sudo: yes
      env:
        - TOX_ENV=py38
        - MBTEST_VERSION=2.0
    - python: 3.8
      sudo: yes
      env:
        - TOX_ENV=py38
        - MBTEST_VERSION=1.16
before_install:
  - nvm install 12
  - pip install --upgrade tox
install:
  - python --version
  - pip --version
  - node --version
  - npm --version
  - npm install mountebank@"${MBTEST_VERSION:-2.2}" --production
script:
  - tox -e $TOX_ENV
