name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.8', '3.7', '3.6', 'pypy-3.6', '3.10.0-alpha - 3.10.0']
        node-version: [15.x]
        mbtest-version: ["2.4", "2.1", "2.0", "1.16"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Install mbtest ${{ matrix.mbtest-version }}
        env:
          MBTEST_VERSION: ${{ matrix.mbtest-version }}
        run: npm install mountebank@$MBTEST_VERSION --production
      - name: Run Tests
        env:
          MBTEST_VERSION: ${{ matrix.mbtest-version }}
        # Run tox using the version of Python in `PATH`
        run: tox -e py

  coverage:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Install mbtest
        run: npm install mountebank@2.4 --production
      - name: Check coverage
        env:
          MBTEST_VERSION: "2.4"
        run: tox -e coverage

  check:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Check format
        run: tox -e check-format
      - name: Lint
        run: tox -e flake8
      - name: Security checks
        run: tox -e bandit,safety
      - name: Check types
        run: tox -e mypy
      - name: Build docs
        run: tox -e docs
