name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.9, 3.8, 3.7]
        node-version: [15.x]
        mbtest-version: [2.4, 2.1, 2.0, 1.16]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Install mbtest
        env:
          MBTEST_VERSION: ${{ matrix.mbtest-version }}
        run: npm install mountebank@$MBTEST_VERSION --production
      - name: Run Tests
        env:
          MBTEST_VERSION: ${{ matrix.mbtest-version }}
        # Run tox using the version of Python in `PATH`
        run: tox -e py
      - name: Check coverage
        if: matrix.python == 3.9 && matrix.mbtest-version == 2.4
        run: tox -e coverage
      - name: Check format
        if: matrix.python == 3.9 && matrix.mbtest-version == 2.4
        run: tox -e check-format
      - name: Lint
        if: matrix.python == 3.9 && matrix.mbtest-version == 2.4
        run: tox -e flake8
      - name: Security checks
        if: matrix.python == 3.9 && matrix.mbtest-version == 2.4
        run: tox -e bandit,safety
      - name: Check types
        if: matrix.python == 3.9 && matrix.mbtest-version == 2.4
        run: tox -e mypy
      - name: Build docs
        if: matrix.python == 3.9 && matrix.mbtest-version == 2.4
        run: tox -e docs
